### ISSUE TITLE
Devhub Issue: Steps to join Pathfinder Rocket.Chat - Desktop  App installation FAQ?

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/reggie-web#44]
I'm wondering if we could add some FAQ content on using deskt opapps? We're getting questions about which work and how to install these properly. Particularly on Windows.

**Comment by ShellyXueHan** [comment]
@filiy Has been working on the FAQ for rocke.chat. It'll be available on chat and devhub afterwards. Closing as duplicate.
