### ISSUE TITLE
Devhub Issue: Steps to join Pathfinder Rocket.Chat [short description here]

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/reggie-web#45]
> path: (do not delete) https://github.com/bcgov/reggie-web/blob/master/UserInstructions.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Community-Enablers-and-Events/Steps-to-join-Pathfinder-Rocket.Chat

## Devhub Content Issue

this should be a documentation not a tool

**Comment by ShellyXueHan** [comment]
@patricksimonian looks like you've update the type to documentation already, thanks!
Closing this issue.
