### ISSUE TITLE
Devhub Issue: Steps to join Pathfinder Rocket.Chat [short description here]

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/reggie-web#47]
> path: (do not delete) https://github.com/bcgov/reggie-web/blob/master/UserInstructions.md
 > (do not delete) devhub page: /Steps-to-join-Pathfinder-Rocket.Chat

## Devhub Content Issue

@ShellyXueHan - wondering if we could add some content to this page to make the most of you helping me overcome the "Houston, we have a problem" problem with the desktop app?

I'd be happy to draft and send a pull request, if you can direct me to where the content is?

**Comment by mark-a-wilson** [comment]
Note to self: 
Here's the place to download version 2.14:
https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.14.7

**Comment by ShellyXueHan** [comment]
@mark-a-wilson this is the markdown file with the content showing on devhub: https://github.com/bcgov/reggie-web/blob/master/UserInstructions.md 
It'd be great if you could add a trouble shooting section!

**Comment by ShellyXueHan** [comment]
changes has been in place, closing
