### ISSUE TITLE
Devhub Issue: Steps to join Pathfinder Rocket.Chat [short description here]

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/reggie-web#49]
> path: (do not delete) https://github.com/bcgov/reggie-web/blob/master/UserInstructions.md
 > (do not delete) devhub page: /Steps-to-join-Pathfinder-Rocket.Chat

## Devhub Content Issue
Do we have a description of what Rocket.chat is somewhere? It would be ideal to have a sentence or two that describes why someone might join. Perhaps something like:

"Rocket.Chat a community building and team messaging tool. The Pathfinder rocket.chat is used by people in the BC Public Service who are building digital products and learning how to work a as a community to build the best practices of digital government in BC."

**Comment by ShellyXueHan** [comment]
updates added here: https://github.com/bcgov/devhub-resources/pull/28
