### ISSUE TITLE
Devhub Issue: Steps to join Pathfinder Rocket.Chat - invitation link is invalid

### ISSUE THREAD

**Issue by rkuyvenhoven** [bcgov/reggie-web#50]
> path: (do not delete) https://github.com/bcgov/reggie-web/blob/master/UserInstructions.md
 > (do not delete) devhub page: undefined

Attempting to join Rocket.chat and after clicking invite link, logging in and submitting business contact information I got a "Your invitation link is invalid, please get invited again" message.

I received a new invite and tried logging in again.  Received the "Your invitation link is invalid, please get invited again" message again.

The email address associated with my IDIR and GitHub accounts is the same address my invite was sent to.

**Comment by jeremy-vernon-bcgov** [comment]
It looks like there's some case-sensitivity where maybe there shouldn't be - we were able to get the invite to work with the same email address with local-part _in lower case_.

**Comment by ShellyXueHan** [comment]
email invitation is now non-case-sensitive. Closing this issue.
