### ISSUE TITLE
Devhub Issue: Steps to join Pathfinder Rocket.Chat [Use of Rocket.Chat]

### ISSUE THREAD

**Issue by spassmor** [bcgov/reggie-web#51]
> path: (do not delete) https://github.com/bcgov/reggie-web/blob/master/UserInstructions.md
 > (do not delete) devhub page: /Steps-to-join-Pathfinder-Rocket.Chat

## Devhub Content Issue
Is the use of Rocket.Chat solely for the ExchangeLab use or can any government employee create a 
group and use it for team communication?

**Comment by ShellyXueHan** [comment]
this is surely open for users to create group chat/channels for their team. Please refer to the https://chat.pathfinder.gov.bc.ca/home for `Channel How-To`
