### ISSUE TITLE
Invitation Link Invalid

### ISSUE THREAD

**Issue by kathydo** [bcgov/reggie-web#53]
Hi there, 

I am trying to invite myself as a new user in rocketchat but get the message, "Your invitation link is invalid, please get invited again". My current Rocket Chat is authenticated by my IDIR, and my new account I want to set up using my personal email. Can anyone please assist?

Thank you! 😊

**Comment by ychung-mot** [comment]
Hi

Not sure it will resolve the issue but try to use the version 2.14.7.

Thanks,
Young-Jin Chung

**Comment by kathydo** [comment]
thank you for the suggestion @ychung-mot ! I just created a new account using my github instead of through inviting myself as new user.. so I got what I needed but this "invalid invitation" issue might still come up..!
